var searchData=
[
  ['getacceleratorconfig',['getAcceleratorConfig',['../classConfigLoader.html#ab7d4cd59d6c3055e12020894ac62014b',1,'ConfigLoader']]],
  ['getparticlesconfig',['getParticlesConfig',['../classConfigLoader.html#a9240923bd59770bd810b9f1e2321e5a4',1,'ConfigLoader']]],
  ['getsimulationconfig',['getSimulationConfig',['../classConfigLoader.html#ab9bf48369cbdd85709bc72ce4245aae4',1,'ConfigLoader']]],
  ['getstorageconfig',['getStorageConfig',['../classConfigLoader.html#adfc18fd163cbcf40281e11530002a45b',1,'ConfigLoader']]],
  ['gnuplot',['Gnuplot',['../classGnuplot.html',1,'Gnuplot'],['../classGnuplot.html#a187eb517b362cf379492fe7f1621ee50',1,'Gnuplot::Gnuplot(const std::string &amp;style=&quot;points&quot;)'],['../classGnuplot.html#a8ceac5808e42665c1dee305ae7ea9070',1,'Gnuplot::Gnuplot(const std::vector&lt; double &gt; &amp;x, const std::string &amp;title=&quot;&quot;, const std::string &amp;style=&quot;points&quot;, const std::string &amp;labelx=&quot;x&quot;, const std::string &amp;labely=&quot;y&quot;)'],['../classGnuplot.html#a24327b6116c71acdc195eadf665c67cb',1,'Gnuplot::Gnuplot(const std::vector&lt; double &gt; &amp;x, const std::vector&lt; double &gt; &amp;y, const std::string &amp;title=&quot;&quot;, const std::string &amp;style=&quot;points&quot;, const std::string &amp;labelx=&quot;x&quot;, const std::string &amp;labely=&quot;y&quot;)'],['../classGnuplot.html#a14191e89154f2716608f6907975cc012',1,'Gnuplot::Gnuplot(const std::vector&lt; double &gt; &amp;x, const std::vector&lt; double &gt; &amp;y, const std::vector&lt; double &gt; &amp;z, const std::string &amp;title=&quot;&quot;, const std::string &amp;style=&quot;points&quot;, const std::string &amp;labelx=&quot;x&quot;, const std::string &amp;labely=&quot;y&quot;, const std::string &amp;labelz=&quot;z&quot;)']]],
  ['gnuplotexception',['GnuplotException',['../classGnuplotException.html',1,'']]]
];
